print("Chad's new file")
print("Chad's new file")
print("Chad's new file")
print("Chad's new file")
print("Chad's new file")
print("Chad's new file")
print("Chad's new file")
print("Chad's new file")
print("What up")
print("What up")
print("What up")
print("What up")
print("What up")
print("What up")
